SAM2BAM_TARGETS=`{find -L ../data/ -name '*.sam' \
	| sed -e 's#\.\./data/#../results/./#g' \
		-e 's#\.sam#.bam#g' \
}

sam2bam:V: $SAM2BAM_TARGETS

clean:V:
	rm $SAM2BAM_TARGETS || true


../results/%.bam:		../data/%.sam
	mkdir -p `dirname $target`
	samtools  view \
		-b \
		-S \
		$prereq \
		-o $target
