#!/bin/sh
#set -x # uncomment for debug

usage() {
cat << EOF
$0 <filename>

There must exist <filename>.md5 containing the checksum for <filename>.
Only one file must be named.

EOF
exit 1
}

main() {
  local FILE="$1"
  [ -r "$FILE".md5 ] || usage
  (
    cd `dirname "$FILE"`
    md5sum -c `basename "$FILE"`.md5 && touch `basename "$FILE"`.ok
  )
}

main "$@"
